### PR TITLE
Initialise barriers Fixes #22

### LINKED ISSUE #22: Initialise Barriers
1. Declare the list of Barriers in `flappy_bird.pde` as `ArrayList<Barrier> barriers = new ArrayList<Barrier>();`
2. To add a new barrier at appropriate time, add the following snippet in the `flappy_bird.pde`'s `draw` function
```
if (frameCount % 75 == 0) 
  {
    barriers.add(new Barrier());
  }
```
3. For barriers to be printed at appropriate locations its x-coordinate needs to be updated and initialised appropriately
* Declare `int wid = 400;` in `flappy_bird.pde` to set appropriate distance between the barriers.
*  In `class Barrier` in `barrier.pde`. Initialise `x` in the constructor `class Barrier` as `x = wid + w;`.
* Declare a `barrier_speed` in the `class Barrier` for maintaining distance between pipes as `float barrier_speed = 3;`
* To update the distances for each barrier, create an `update` function with `void` return type and update the values by writing `x-=barrier_speed;` in it.

### PR DESCRIPTION
**Pull request by karolade**
Fixes #22

### CODE REVIEW

**Comment by karolade** [comment]
Thanks:)
what do you mean by "needs to come there"?

**Comment by priyanshisharma** [comment]
I mean that the phrase needs to be present in the PR description (notice how I modified it before merging) :-)

**Comment by karolade** [comment]
Ahh I see, I'll make sure to do that!

Thanks for letting me know

**Comment by priyanshisharma** [comment]
Sure, awesome! 😄 
Notice how the linked issues for the PR and linked PR for the issue changes once you do that ;)

**Pull request merged**
